"""
Varsayilan coklu bolum sablonu ve birlestirilmis Markdown uretimi.

Streamlit veya `run_paper_pipeline` bu listeyi tek indeks uzerinde ardışık Writer
cagrılarıyla tam makale taslagina donusturur.
"""

from __future__ import annotations

import re
from typing import Any


_REF_BLOCK_RE = re.compile(
    r"PART\s+2\s+[—\-–]\s+REFERENCES\s*:?\s*\n(.*?)(?=PART\s+3\s+[—\-–]|\Z)",
    re.IGNORECASE | re.DOTALL,
)
_REF_LINE_RE = re.compile(r"^\s*\[(\d+)\]\s+(.+?)\s*$")


def _extract_references_from_body(text: str) -> tuple[str, list[str]]:
    """
    Section body'sinden 'PART 2 — REFERENCES' blogunu cikarir; (temizlenmis_body, [ref_metinleri]) doner.
    Sadece [n] ile baslayan satirlari ref olarak alir; gerisi atilir.
    """
    refs: list[str] = []
    cleaned = text
    m = _REF_BLOCK_RE.search(text)
    if m:
        block = m.group(1)
        for line in block.splitlines():
            mm = _REF_LINE_RE.match(line)
            if mm:
                refs.append(mm.group(2).strip())
        cleaned = _REF_BLOCK_RE.sub("", text).strip()
    return cleaned, refs


def _dedupe_references(all_refs: list[str]) -> list[str]:
    """
    URL bazli oncelikli tekille me; URL bulunmayan referanslarda kucuk-harf normalize
    edilmis tam metin anahtari kullanir. Ayni repo URL'si farkli format/yıl ile birden
    fazla kez gelse de tek kez listeye girer; ilk gorulen sıra korunur.
    """
    url_re = re.compile(r'https?://[^\s,\]]+')
    seen_urls: set[str] = set()
    seen_text: set[str] = set()
    out: list[str] = []
    for r in all_refs:
        m = url_re.search(r)
        if m:
            url = m.group(0).rstrip('.,;')
            if url in seen_urls:
                continue
            seen_urls.add(url)
        else:
            key = " ".join(r.lower().split())
            if key in seen_text:
                continue
            seen_text.add(key)
        out.append(r)
    return out


def _strip_traceability_tables(text: str) -> str:
    """
    Govde icindeki traceability markdown tablolarini siler; bu tablolar bazen
    PART 1 — PAPER BODY akisinin icinde TRACEABILITY: marker'indan ONCE de gorunup
    cleaned_body'ye sizip Word'de BodyText olarak basiliyor. Yontem: header satirinda
    'claim id' veya 'claim summary' geciyorsa, sonraki tum '|' ile baslayan ardisik
    satirlari (table govdesi) atla; bos veya '|' ile baslamayan ilk satirda mod kapanir.
    """
    lines = text.splitlines()
    out: list[str] = []
    in_table = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("|"):
            lower = stripped.lower()
            if "claim id" in lower or "claim summary" in lower:
                in_table = True
            if in_table:
                continue
        else:
            in_table = False
            out.append(line)
    return "\n".join(out)

# (bolum basligi, bolum hedefi) — hedefler CONTEXT ile uyumlu kisa talimat olmali.
# Tam makale Markdown birlestirmesinde Writer henuz uretmiyorsa kullanilan varsayilanlar.
DEFAULT_COMBINED_PAPER_TITLE = "Code-to-Paper — combined draft"
DEFAULT_COMBINED_ABSTRACT_PLACEHOLDER = (
    "Abstract not auto-generated by pipeline; replace before submission."
)
DEFAULT_COMBINED_KEYWORDS_PLACEHOLDER = (
    "code-to-paper, retrieval-augmented generation, documentation, LLM"
)

DEFAULT_PAPER_SECTIONS: list[tuple[str, str]] = [
    (
        "Introduction and motivation",
        "Introduce the automated code-to-paper workflow and the analyzed repository as the "
        "subject system; state scope and intended reader takeaway using only evidenced facts.",
    ),
    (
        "System architecture and implementation",
        "Explain repository ingestion, hierarchical indexing, planner-driven multi-query retrieval, "
        "and the academic writer stage; map claims strictly to repository evidence.",
    ),
    (
        "Limitations and future work",
        "Summarize evidenced constraints (e.g., reliance on external LLM APIs, retrieval bounds); "
        "do not invent a roadmap not supported by the codebase.",
    ),
]


def combine_paper_markdown(
    *,
    repo_url: str,
    commit_hash: str,
    section_results: list[dict[str, Any]],
    paper_title: str = "",
    abstract_text: str = "",
    keywords_text: str = "",
) -> str:
    """
    Bolum Writer ciktilarini tek Markdown dosyasinda birlestirir; TRACEABILITY bloklarini sonda toplar.

    Ust kisim: makale basligi + Abstract/Keywords satirlari (em dash); export katmani
    write_markdown_with_ieee_styles icindeki Abstract/Keywords on ek algisiyla stillenir.
    Bos string gelirse DEFAULT_* sablonlari kullanilir.
    """
    title = (paper_title or "").strip() or DEFAULT_COMBINED_PAPER_TITLE
    abst = (abstract_text or "").strip() or DEFAULT_COMBINED_ABSTRACT_PLACEHOLDER
    keys = (keywords_text or "").strip() or DEFAULT_COMBINED_KEYWORDS_PLACEHOLDER

    # IEEE makale govdesinde Repository/Commit satirlari yer almaz; bunlar yalnizca traceability
    # bilgisi olarak ic loglarda kalir. Kullanici istegi: makale govdesi sade tutulsun.
    _ = (repo_url, commit_hash)

    lines: list[str] = [
        f"# {title}",
        f"Abstract\u2014{abst}",
        f"Keywords\u2014{keys}",
        "",
    ]
    trace_chunks: list[str] = []
    all_refs: list[str] = []

    for block in section_results:
        section_heading = str(block.get("section_title") or "Section").strip()
        body = str(block.get("writer_text") or "").strip()
        cleaned_body, section_refs = _extract_references_from_body(body)
        cleaned_body = _strip_traceability_tables(cleaned_body)
        all_refs.extend(section_refs)
        lines.append(f"## {section_heading}")
        lines.append("")
        lines.append(cleaned_body)
        lines.append("")
        meta = block.get("writer_metadata") or {}
        tr = str(meta.get("traceability") or "").strip()
        if tr:
            trace_chunks.append(f"### {section_heading}\n\n{tr}\n")

    deduped = _dedupe_references(all_refs)
    if deduped:
        lines.append("## References")
        lines.append("")
        for i, ref in enumerate(deduped, start=1):
            lines.append(f"[{i}] {ref}")
        lines.append("")

    # --- Faithfulness Audit (BEFORE the TRACEABILITY aggregator) ---
    audit_chunks: list[str] = []
    total_weight = 0
    weighted_sum = 0.0
    for block in section_results:
        f = block.get("faithfulness")
        if not f:
            continue
        count = int(f.get("claim_count") or 0)
        if count == 0:
            continue
        weighted_sum += float(f.get("score", 0.0)) * count
        total_weight += count
        sec_heading = str(block.get("section_title") or "Section").strip()
        sec_label = f.get("label", "low")
        sec_score = f.get("score", 0.0)
        chunk_lines: list[str] = [
            f"### {sec_heading}",
            "",
            f"Faithfulness score: {sec_score:.2f} ({sec_label})",
            "",
            "| Claim | Verdict | Source | Notes |",
            "|-------|---------|--------|-------|",
        ]
        for c in (f.get("claims") or []):
            verdict = str(c.get("verdict", "unsupported"))
            verdict_icon = {"supported": "✓", "partial": "~", "unsupported": "✗"}.get(verdict, "?")
            src = f"{c.get('source_file', '')} : {c.get('lines', '')}"
            note = (c.get("judge_note") or "").replace("|", "\\|")
            cid = c.get("id", "")
            summary = (c.get("summary") or "")[:80]
            chunk_lines.append(f"| {cid}: {summary} | {verdict_icon} {verdict} | {src} | {note} |")
        chunk_lines.append("")
        audit_chunks.append("\n".join(chunk_lines))

    if audit_chunks:
        paper_score: float | None = None
        paper_label: str | None = None
        if total_weight > 0:
            paper_score = round(weighted_sum / total_weight, 3)
            paper_label = "high" if paper_score >= 0.8 else "medium" if paper_score >= 0.6 else "low"
        lines.append("---")
        lines.append("")
        lines.append("## Faithfulness Audit")
        lines.append("")
        if paper_score is not None:
            lines.append(f"Aggregate paper-wide faithfulness: {paper_score:.2f} ({paper_label}).")
        else:
            lines.append("Aggregate paper-wide faithfulness: unavailable.")
        lines.append("")
        lines.extend(audit_chunks)

    if trace_chunks:
        lines.append("---")
        lines.append("")
        lines.append("## TRACEABILITY (all sections)")
        lines.append("")
        lines.extend(trace_chunks)

    return "\n".join(lines).strip()
